### ISSUE TITLE
学生会oa官网是多少？

### ISSUE THREAD

**Issue by JerryLoveZhiXin** [zhxsuwebgroup/SUsage#10]
是OA不是官网……
官网一早就404了，除了校运会之外没一天开放的……

**Comment by GhostShadowTan** [comment]
我们还没go live……

**Comment by JerryLoveZhiXin** [comment]
e……不得不承认我当初选择帮团委开发是明智的……

**Comment by df7c5117** [comment]
由于开发工期长（不像团委可以直接使用现成的bootstrap）OA平台仍处于milestone阶段，主域名尚未正式启用。

本学期内该系统将正式上线。届时我们将公布域名。

另外，官网并没有不开放，为了网页设计的需要，我们解析了一个域名md.ttkttk.tk【然而上面只放了个设计稿并没有什么卵用

**Comment by GhostShadowTan** [comment]
……同学，这里不是引战的地方

**Comment by GhostShadowTan** [comment]
OA平台本来的预期就是在换届后使用，现在go live都只能A测。我们组内也很欣赏你们做的网站，只是你们在debug的态度上实在需要改正。如果有一台电脑不能正常打开网站，你就应该去检查你的源代码，而不是一句css,js没加载完全就解决了事。程序员的初衷不是做个作品出来炫耀。

**Comment by JerryLoveZhiXin** [comment]
学长请原谅……
怪我这个初二不识大局的我……
对不起……

**Comment by GhostShadowTan** [comment]
没事，你要走的路还长，多学习，初二能参与这种项目对以后的学习都有很大帮助

**Comment by JerryLoveZhiXin** [comment]
多谢学长谅解。

**Comment by JerryLoveZhiXin** [comment]
那请问你们是怎么测试的？milestone是啥？

**Comment by df7c5117** [comment]
milestone（n），简称m（n），即为alpha测试阶段前的阶段，中文直译里程碑。

这个阶段代号是为了在项目正式成型之前找出百分之八九十的低级故障和算法错误，同时会加入对未来新功能的展望和demo。由于算法和内部系统还没有整合，现在我们的项目停留在UI成型阶段，这也是为什么我们暂停了这个项目的开发，正在转型为内部结构的组织优化。

由于我们的主要文件都采用html格式，无需像php需要服务器端调试，所以欢迎各位下载到本地前来查找bug。milestone时期，机不可失，失不再来！

**Comment by JerryLoveZhiXin** [comment]
哦好的。我去看看嘻嘻~谢谢学长们对我的谅解和给我的知识。

**Comment by df7c5117** [comment]
现在孩子们不得了啊……想想我们那个时候还在干嘛呢……
所以能在这方面继续涉足和进步，会对你之后对项目的解决、问题的思考、技术的提升都会有不小的作用。

**Comment by GhostShadowTan** [comment]
我在参加NOIP，手动滑稽

**Comment by JerryLoveZhiXin** [comment]
NOIP是啥……
确实我以后想往这一行走，所以我才看到团委。
