### ISSUE TITLE
[help wanted]help_unfixed_20160305_post：发布系统关于输入框长度判定、编辑公告时刷新页面提示等机制的问题

### ISSUE THREAD

**Issue by df7c5117** [zhxsuwebgroup/SUsage#11]
目前，发布系统关于输入框长度判定、编辑公告时刷新页面提示等机制代码功能不全，存在问题并且需要协助解决完善。

**Comment by JerryLoveZhiXin** [comment]
能不能用php

**Comment by JerryLoveZhiXin** [comment]
js可以检测编辑框长度。
$("#编辑框id").val().length<100
希望我给您的代码有所帮助(๑•̀ω•́๑)

**Comment by df7c5117** [comment]
马克并研习中

**Comment by JerryLoveZhiXin** [comment]
@df7c5117 啥意思？

**Comment by df7c5117** [comment]
就是了解了，正在着手试验。

**Comment by JerryLoveZhiXin** [comment]
哦那就是有帮助吗
初二鸡一名可不可以给我点认可……

**Comment by df7c5117** [comment]
赞同并且感谢并且有帮助

**Comment by JerryLoveZhiXin** [comment]
……
好吧谢谢学长支持！

> ZHXTW Project Assist Developer
> Jerry Cheung
