### ISSUE TITLE
[Standard]Note_20160305_global：激活码算法暂行方法

### ISSUE THREAD

**Issue by GhostShadowTan** [zhxsuwebgroup/SUsage#13]
# SUsage A测激活码暂行办法
## 为什么要这个算法
为了防止在A测中，随意注册账号会带来潜在的流量问题，SUsage的人员账号注册采用激活制，根据算法表，与SU工作人员的个人信息相结合算出激活码再与部门序号相匹配，即可激活账号
### SUsage序号部分：
由部门、学生会届数、特别识别码、部长（主席团）授权码组成

### 部门表：
00主席团
01公关部
02社联
03文娱部
04体育部
05学术部
06内务部
07广播站
08宣传部
09电视台
10电脑部

### 届数表：
使用16进制（一层加密） 即37届为25,38届为26,42届为2a

### 特别识别码：
由系统自动生成，为该同学姓名汉字区位表码之差（三字或四字姓名取前两位）
如谭为4423 天为4476
所以特别识别码为53（值得注意的是若差为三位数或以上，则选用末两位）

### 部长（主席团）授权码：
由部长（主席）亲自选择的无规律的3位码（可包含a-z,0-9）
因为无规律可循，所以授权码的加密等级为无对应表密码，最高加密等级。

因为授权码存在批量申请时难以处理的情景，所以大规模测试时，推荐放弃该码

### 激活码部分：
激活码的加密方式为
注册人8位生日的16进制数（如，谭天为1310a4b），加上以凯撒密码（前推八格）组成的姓名简写如若姓名简写为hhh hhhh 则转码为aaa aaaa。（激活码只是对身份的确认）

# 最后讲一讲
SUPC网页组内部管理人员的注册方法，在群里公布，毕竟github上谁都能看到我们的加密方法……

**Comment by df7c5117** [comment]
你问我滋词不滋词我说滋词我就明确告诉你

**Comment by zhangjingye03** [comment]
用单向散列函数或者直接生成uuid多容易，记录到数据库就可以了，还能有效防止枚举
弄的越烦，越难写代码，go live计划时间就越长
![滑稽](https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3800431383,2458432473&fm=116&gp=0.jpg)

**Comment by zhangjingye03** [comment]
> 随意注册账号会带来潜在的流量问题
你可以去大网站抓抓请求，看看哪个网站因为注册而耗得流量比其他的静态资源多

**Comment by GhostShadowTan** [comment]
亲爱的
我指的是ttk出现过的刷评论问题

**Comment by zhangjingye03** [comment]
真是抱歉ttk的20G流量是我刷的，刷的是图片 :joy:

**Comment by JerryLoveZhiXin** [comment]
……够够的了

**Comment by JerryLoveZhiXin** [comment]
说好的非引战地区在哪？

**Comment by zhangjingye03** [comment]
当年简单的小脚本，连你们亲爱的王爷组组长用了cloudflare都挡不住
当时班上的同学都在专心复习，我们这一对同桌都在玩网络战

for i in $(seq 0 65536)
do
a=`cat /proc/sys/kernel/random/uuid`
echo $i
curl -m 2 --connect-timeout 1 -d $a http://sport.zhxsu.com/file/mainpic.png > /dev/null
done

**Comment by JerryLoveZhiXin** [comment]
为何是404……
执信学生会官网怎么了……

**Comment by JerryLoveZhiXin** [comment]
算了……旁观……
写代码去……

**Comment by df7c5117** [comment]
我只想发喷水的表情

**Comment by GhostShadowTan** [comment]
我也是……

**Comment by JerryLoveZhiXin** [comment]
@df7c5117 @GhostShadowTan 
建议用暴漫hhh

**Comment by GhostShadowTan** [comment]
……

**Comment by JerryLoveZhiXin** [comment]
我觉得挺好的
哈哈哈哈哈哈哈哈
