### ISSUE TITLE
给点小建议

### ISSUE THREAD

**Issue by zhangjingye03** [zhxsuwebgroup/SUsage#14]
![bug](http://i11.tietuku.com/424a5e028196f8dd.jpg)

* login.html中，chrome等浏览器的自动完成黄色框会盖住material-design的风格，极其难看，建议增加一个hidden的input并赋予"username"作为其name值
* Wiki的发布系统中，
    1.2.5 top锚标记可以不用，直接用$("body").animate({scrollTop:0});即可
    1.2.9 C点 if(!$("#xxx").val()){alert("你还啥都没写呢！");return;}
* 这么无聊的issue项目分类有必要么...看着看着你们自己就烦了

**Comment by df7c5117** [comment]
马克并研习中

**Comment by GhostShadowTan** [comment]
受教了

**Comment by JerryLoveZhiXin** [comment]
……

**Comment by df7c5117** [comment]
另外，图好像挂了？

**Comment by JerryLoveZhiXin** [comment]
貌似是……

**Comment by zhangjingye03** [comment]
http://i11.tietuku.com/424a5e028196f8dd.jpg

**Comment by JerryLoveZhiXin** [comment]
@zhangjingye03 垮图

**Comment by GhostShadowTan** [comment]
这是……老司机发车……
