### ISSUE TITLE
Bug | 导航栏的Bug

### ISSUE THREAD

**Issue by JerryLoveZhiXin** [zhxsuwebgroup/SUsage#16]
## **隔壁前来测试** :joy::joy::joy:

# **Bug详述**
**批斗大会和文件库的导航不见了**
其他都有。

![bug](https://cloud.githubusercontent.com/assets/16716834/13847510/87fad834-ec88-11e5-9283-f67a99ab06bb.jpg)
![bug2](https://cloud.githubusercontent.com/assets/16716834/13847511/881b4baa-ec88-11e5-880f-23cfdef6aebf.jpg)

**Comment by JerryLoveZhiXin** [comment]
@df7c5117 @GhostShadowTan

**Comment by df7c5117** [comment]
哦……这不奇怪，前两天我们大幅度更新了css文件路径，push上去的文件引用地址有些没改，最新的更新已经修复此问题。


……这两天天天背着电脑在学校跑来跑去真是烦死了

**Comment by JerryLoveZhiXin** [comment]
@df7c5117 @zhangjingye03

学长你们都在哪儿开发的？学校？家里？

**Comment by df7c5117** [comment]
我个人是这几个星期把电脑扛回学校然后放学之后在班上或者学工写，周末就在家写。
