### ISSUE TITLE
[help]20160507_background:后台首页要些什么

### ISSUE THREAD

**Issue by JerryLoveZhiXin** [zhxsuwebgroup/SUsage#19]
RT.

我不造后台的首页
需要放些什么。

只要说放些啥就好了，

UI我来想吧。

麻烦了！

**Comment by df7c5117** [comment]
你等会啊……我需要一段时间总结功能需求

**Comment by JerryLoveZhiXin** [comment]
@df7c5117

开发构思文档已经发了。

请在原基础上修改。

首页界面已确定为任务列表。

**Comment by JerryLoveZhiXin** [comment]
@df7c5117

开发构思文档已经发了。

请在原基础上修改。

首页界面已确定为任务列表。
