### ISSUE TITLE
发布系统制作

### ISSUE THREAD

**Issue by GhostShadowTan** [zhxsuwebgroup/SUsage#2]
发布系统已经到了Milestone 5 
前路漫漫

**Comment by df7c5117** [comment]
现已进行至M6，望各位去wiki里找到我撂在那或者标记为有问题的代码review一遍。
**望各位试试文本中的加粗问题** @GhostShadowTan @zhxsuwebgroup

**Comment by df7c5117** [comment]
近期亟待更新：waterfall的数据库连接；waterfall的样式；全局javascript的性能优化；上传功能接口
